### ISSUE TITLE
How to properly include "google-play-services.jar" for this project?

### ISSUE THREAD

**Issue by ProgrammingLife** [zendorx/oxygine-admob#1]
How to properly include "google-play-services.jar" which will work with this project? How to do it?

**Comment by zendorx** [comment]
You can add this line into your gradle build file, for example auth services
> compile 'com.google.android.gms:play-services-auth:9.8.0'

**Comment by ProgrammingLife** [comment]
But where should "google-play-services.jar" be placed to use it with oxygine? Can you provide us with a little example on how to use oxygine-admob with oxygine?

**Comment by zendorx** [comment]
You no need to use jar files if use gradle. Add line in dependencies block

https://github.com/oxygine/oxygine-framework/blob/master/examples/HelloWorld/proj.android/build.gradle

**Comment by zendorx** [comment]
Also required lib already added in this project

> compile 'com.google.android.gms:play-services-ads:9.8.0'

so you need just add oxygine-admob to your project

**Comment by ProgrammingLife** [comment]
Thanks in advance. I'll give it a try. 
By the way, it looks like HelloWorldAdmob contains Facebook example only :) there's no nothing about admob at all :)

**Comment by zendorx** [comment]
I have added instructions check it here
https://github.com/zendorx/oxygine-admob
