### ISSUE TITLE
Trying to add oxygine-admob to my oxygine project

### ISSUE THREAD

**Issue by ProgrammingLife** [zendorx/oxygine-admob#2]
I've just created an empty oxygine project called **AdmTest**. Then I did following steps:
1. I added this line to the **AdmTest/proj.android/project.properties**: 
android.library.reference.2=../../engine/oxygine/oxygine-admob/android

2. I added this line to the file **AdmTest/proj.android/build.gradle**:
```
dependencies {
    compile(project(':oxygine-extension'))
    compile(project(':oxygine-lib')) { exclude module: 'oxygine-extension' }
# this line:
    compile 'com.google.android.gms:play-services-auth:9.8.0'
}

```
3. I've successfully build it (**./build.sh**) but when it was doint the "**ant release**" stage I get the following message:
```
-compile:
    [javac] Compiling 2 source files to /Users/user/projects/engine/oxygine/oxygine-admob/android/bin/classes
    [javac] /Users/user/projects/engine/oxygine/oxygine-admob/android/src/org/oxygine/admob/AdmobAdapter.java:6: error: package com.google.android.gms.ads does not exist
    [javac] import com.google.android.gms.ads.AdListener;
    [javac]                                  ^
    [javac] /Users/user/projects/engine/oxygine/oxygine-admob/android/src/org/oxygine/admob/AdmobAdapter.java:7: error: package com.google.android.gms.ads does not exist
    [javac] import com.google.android.gms.ads.AdRequest;
```

Looks like it doesn't see the "**com.google.android.gms.ads**" package. What do I do wrong? How to detect what's wrong with my config?

**Comment by zendorx** [comment]
I just finished instructions check readme file. With ant you need to add jar files manually into lib folder, this lib does not support ant, you need add it by yourself. I Recommend use gradle as your build system.

**Comment by ProgrammingLife** [comment]
Thanks. I've checked the README.md file. The one thing that I don't understand is that: how the build process will change from the standart: **./build.sh && ant release** to the one when it will use gradle build system? How will it look like then?

**Comment by zendorx** [comment]
https://spring.io/guides/gs/gradle-android/
```
download gradle 2.7
add path to PATH
execute "gradle build" in the proj.android folder
```
